name: Build and Test Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os_arch:
          [
            { os: windows-2022, arch: x64 },
            { os: macos-14, arch: x64 },
            { os: macos-14, arch: arm64 },
            { os: ubuntu-22.04, arch: x64 },
          ]

    runs-on: ${{ matrix.os_arch.os }}

    steps:
      - name: Install conan
        run: pip install conan ninja cmake

      - name: conan cache
        id: conan_cache
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ matrix.os_arch.os }}-${{ matrix.os_arch.arch }}-conan

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Compiler (Windows)
        uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os_arch.os == 'windows-2022'

      - name: Setup Compiler (macOS)
        if: matrix.os_arch.os == 'macos-14'
        run: |
          brew install llvm@18
          echo "/opt/homebrew/opt/llvm@18/bin" >> $GITHUB_PATH
          echo "CC=/opt/homebrew/opt/llvm@18/bin/clang" >> $GITHUB_ENV
          echo "CXX=/opt/homebrew/opt/llvm@18/bin/clang++" >> $GITHUB_ENV

      - name: Setup Compiler and env (Ubuntu 22)
        if: matrix.os_arch.os == 'ubuntu-22.04'
        run: |
          echo "CC=gcc-12" >> $GITHUB_ENV
          echo "CXX=g++-12" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$PWD/libxdaq/linux/x86_64/lib/xdaq/plugin:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Conan export package and test
        run: |
          conan config install .github/conan_profiles/${{ matrix.os_arch.os }}-${{ matrix.os_arch.arch }} -tf profiles
          conan install . --build missing --profile:all ${{ matrix.os_arch.os }}-${{ matrix.os_arch.arch }}
          conan export-pkg . --profile:all ${{ matrix.os_arch.os }}-${{ matrix.os_arch.arch }}

